import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";
import Navbar from "./_component/Navbar";
import Footer from "./_component/Footer";
import NextAuthProvider from "@/provider/Component/nextauth.providers";
import Providers from "@/provider/Component/ReactQueryProvider.provider";
import { ToastContainer } from "react-toastify";

const Encode = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight:['300','400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${Encode.className} antialiased`}>
        <Providers>
           <ToastContainer/>
        <div className="flex flex-col justify-between min-h-screen">
          <NextAuthProvider>
          <Navbar/>
          <div className="container">
            {children}
            </div>
          <Footer/>
          </NextAuthProvider>
        </div>
        </Providers>
      </body>
    </html>
  );
}
